UART: convert to nmigen
GlasgowEmbedded/glasgow pull request #228
Opened 2020-11-08 23:09 UTC by attie

Addresses `interface.uart` item from #150.

2020-11-09 00:59 UTC, attie commented
I'm currently unable to replicate the failures on my computer... will investigate later.

```
venv:$ python -W ignore::DeprecationWarning test.py -k 'glasgow.gateware.uart*'
.............
----------------------------------------------------------------------
Ran 13 tests in 0.823s

OK
```

2020-11-09 01:38 UTC, attie commented
I'm aware of the failed test, but can't replicate it here... When running _all tests_, I see the following (same error, different test).

```
venv:$ python -W ignore::DeprecationWarning test.py
[...]
======================================================================
ERROR: test_build (glasgow.applet.memory.prom.MemoryPROMAppletTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/attie/proj_local/glasgow/glasgow/software/glasgow/applet/memory/prom/__init__.py", line 872, in test_build
    self.assertBuilds()
  File "/home/attie/proj_local/glasgow/glasgow/software/glasgow/applet/__init__.py", line 232, in assertBuilds
    target.build_plan().execute()
  File "/home/attie/proj_local/glasgow/glasgow/software/glasgow/target/hardware.py", line 118, in execute
    products  = self.lower.execute_local(build_dir)
  File "/home/attie/proj_local/glasgow/nmigen/nmigen/build/run.py", line 98, in execute_local
    subprocess.check_call(["sh", "{}.sh".format(self.script)])
  File "/home/attie/.bin/python3.8.2/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sh', 'build_top.sh']' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 238 tests in 168.288s

FAILED (errors=1, skipped=7)
```

When running the test specifically, I see:

```
venv:$ python -W ignore::DeprecationWarning test.py -vk glasgow.applet.interface.uart.UARTAppletTestCase
test_build (glasgow.applet.interface.uart.UARTAppletTestCase) ... Warning: Wire top.$flatten\i2c_target.\bus.$verilog_initial_trigger has an unprocessed 'init' attribute.
Warning: Wire top.$verilog_initial_trigger has an unprocessed 'init' attribute.
ok
test_loopback (glasgow.applet.interface.uart.UARTAppletTestCase) ... ok

----------------------------------------------------------------------
Ran 2 tests in 5.379s

OK
```

I have also seen errors such as below, when my code is bad. I was considering raising an issue, though not sure if it's nMigen or Glasgow.

```
venv:$ glasgow test uart
I: g.cli: testing applet 'uart'
test_build (glasgow.applet.interface.uart.UARTAppletTestCase) ...
ERROR: Can't open input file `/tmp/yosys-abc-3pHqzP/output.aig' for reading: No such file or directory
ERROR
Traceback (most recent call last):
  File "/home/attie/proj_local/glasgow/glasgow/software/glasgow/applet/interface/uart/__init__.py", line 381, in test_build
    self.assertBuilds()
  File "/home/attie/proj_local/glasgow/glasgow/software/glasgow/applet/__init__.py", line 232, in assertBuilds
    target.build_plan().execute()
  File "/home/attie/proj_local/glasgow/glasgow/software/glasgow/target/hardware.py", line 118, in execute
    products  = self.lower.execute_local(build_dir)
  File "/home/attie/proj_local/glasgow/nmigen/nmigen/build/run.py", line 98, in execute_local
    subprocess.check_call(["sh", "{}.sh".format(self.script)])
  File "/home/attie/.bin/python3.8.2/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sh', 'build_top.sh']' returned non-zero exit status 1.
```

2020-11-09 01:44 UTC, whitequark commented
It is not your responsibility to fix the build error. (As in, I'll look into it, but not necessarily soon.)

2020-11-09 01:45 UTC, attie commented
Ok, thanks.

The gateware and applet work, I've had to tweak things for the `nmigen.compat` -> `nmigen`, but I _think_ it should be fine as it is now.

2020-11-10 02:32 UTC, whitequark commented
Okay, so the error is:
```
The command has to terminate. Boxes are not in a topological order.
The following information may help debugging (numbers are 0-based):
Input 0 of BoxA 1 (1stCI = 474; 1stCO = 1) has TFI with CI 509,
which corresponds to output 1 of BoxB 34 (1stCI = 508; 1stCO = 38).
In a correct topological order, BoxB should precede BoxA.
Error: Abc_CommandAbc9If(): Mapping of GIA has failed.
** cmd error: aborting 'source /tmp/yosys-abc-000000/abc.script'
ERROR: Can't open input file `/tmp/yosys-abc-000000/output.aig' for reading: No such file or directory
E.ABC command line: "source /tmp/yosys-abc-000000/abc.script".
```

Is your Yosys a very recent build from git? If not, that's probably why you don't see it. Try upgrading it, or use the CI configuration file to use YoWASP on your machine.

2020-12-29 06:35 UTC, whitequark commented
@attie Can you rebase? I think post #251 the failure might be fixed.

2020-12-29 08:13 UTC, whitequark commented on software/glasgow/gateware/uart.py
> +        self.max_bit_cyc = max_bit_cyc or bit_cyc
This is not equivalent in all cases (`max_bit_cyc=0` would have different behavior). Although it makes little difference here, I strongly prefer explicit `is None`.

2020-12-29 08:14 UTC, whitequark commented on software/glasgow/gateware/uart.py
> +        m.submodules += self.dut
I think you can just `return self.dut`.

2020-12-29 08:14 UTC, whitequark requested changes
See inline comments.

2020-12-29 09:53 UTC, whitequark submitted a review, later dismissed
Code LGTM, not sure why tests are failing...

2020-12-29 10:03 UTC, attie commented
My fault, I added a missing `.oe.eq(1)` (the UART Tx was non-functional), and did realise that I needed to update `Pin(width=1, dir='oe')` too.

2020-12-29 10:16 UTC, whitequark approved these changes

2020-12-29 10:17 UTC, merged

2020-12-29 10:17 UTC, whitequark commented
Thanks!