applet.audio.dac: convert to nmigen
GlasgowEmbedded/glasgow pull request #230
Opened 2020-11-09 00:39 UTC by attie

Addresses `audio.dac` item from #150.

2020-11-09 22:26 UTC, whitequark requested changes

2020-11-09 22:26 UTC, whitequark commented on software/glasgow/applet/audio/dac/__init__.py
> +        self.pads = pads
These all should be private.

2020-11-09 22:26 UTC, whitequark commented on software/glasgow/applet/audio/dac/__init__.py
> +        self.channels = [
I would create channels in `elaborate` to avoid having extra state shared between `__init__` and `elaborate`.

2020-11-09 22:26 UTC, whitequark commented on software/glasgow/applet/audio/dac/__init__.py
> +        self.output = output
I would make this `_output`, since it is not a part of the channel's interface (instead it's captured during creation and used internally only). `bits` and `signed` aren't all that useful but are fine as a part of its interface.

2020-11-09 22:37 UTC, attie commented on software/glasgow/applet/audio/dac/__init__.py
> +        self.pads = pads
"_all_" = `pads`, `out_fifo`, `pulse_cyc`, `sample_cyc` and `width`?
`signed` will need to come too if `channels` moves into `elaborate`, but that's fine.

Do you want double underscore privates, or are you expecting single? (e.g: your comment on `_output` above)

2020-11-09 22:47 UTC, attie commented on software/glasgow/applet/audio/dac/__init__.py
> +        self.pads = pads
rebase and push breaks the link 🙈

https://github.com/GlasgowEmbedded/glasgow/pull/230/files#r520159630

2020-11-10 02:25 UTC, whitequark commented on software/glasgow/applet/audio/dac/__init__.py
> +        self.pads = pads
You know, I'm just wrong. I looked and in every other applet the subtarget doesn't have private attributes.

These conventions are getting complicated enough I really should write them down somewhere so that it doesn't take up review bandwidth.

2020-11-10 02:25 UTC, whitequark approved these changes

2020-11-10 02:25 UTC, merged

2020-11-10 02:25 UTC, whitequark commented
Thanks!

2020-11-10 02:31 UTC, attie commented on software/glasgow/applet/audio/dac/__init__.py
> +        self.pads = pads
>  looked and in every other applet the subtarget doesn't have private attributes.

No problem, I was thinking about pushing back for that reason.