Add bitarray implementation to eliminate external dependency
GlasgowEmbedded/glasgow pull request #265
Opened 2021-01-24 15:28 UTC by mndza

This PR is an attempt to address #179. This bitarray implementation follows the interface established by `glasgow.support.bits` while changing the backing storage to an `array()` object. Currently the element size of this array is a byte and not a machine word.

I am not particularly happy with the `byte_reverse` / `byte_reversed` method names to imply in-place modification or not. Also, I am not sure about the correct behavior in those functions when the number of stored bits is not a multiple of a byte. Currently it drops the bits that exceed the bit length after the byte reversal.

Also, while initializing the bitarray from a `bytes` object you need to provide the explicit length in bits. This is because I copied the interface from bytes, but I am not sure if that is the desired operation.

Most of the test cases were copied from `glasgow.support.bits`.

2021-01-25 09:07 UTC, plaes commented on software/glasgow/support/bitarray.py
> +            src = memoryview(src)[start//8:]
From where is this imported?

2021-01-26 23:27 UTC, attie reviewed
@mndza thanks very much for doing this!

I've had a rummage, and found a few issues - sorry!

... this should be a "_request changes_" review, I'm still learning GitHub.

2021-01-26 23:27 UTC, attie commented on software/glasgow/support/bitarray.py
> +            return format(self.to_int(), "0{}b".format(self._len_))
This gives me the same unease as bitarray.setall(), with large values...

2021-01-26 23:27 UTC, attie commented on software/glasgow/support/bitarray.py
> +            self._array_[pos // 8] &= ~(1 << (pos % 8))
These don't respect `self._len_`:

```
>>> x = bitarray.from_bytes(b'\x05', 5)
>>> x
bitarray('00101')
>>> x._len_
5
>>> x[7]
0

>>> x[7] = 1
>>> x._len_
5
>>> x
bitarray('10000101')
```

2021-01-26 23:27 UTC, attie commented on software/glasgow/support/bitarray.py
> +        return "bitarray('{}')".format(self)
I'm not sure what `self` collapses to here, but it also doesn't respect `self._len_` (see comment on `bitarray._getbit()`)

2021-01-26 23:27 UTC, attie commented on software/glasgow/support/bitarray.py
> +        return self & other
Not sure what's going on here, but I don't think it's right...

```
>>> x = bitarray.from_bytes(b'\x05', 5)
>>> x
bitarray('00101')
>>> x & 0x82
bitarray('10000010')
>>> 0x82 & x
bitarray('10000010')
```

2021-01-26 23:27 UTC, attie commented on software/glasgow/support/bitarray.py
> +        self._len_ = max(self._len_, other._len_)
I'm not 100% sure this should be able to change the `bitarray`'s size... humm...

I think I might prefer an exception here.

2021-01-26 23:27 UTC, attie commented on software/glasgow/support/bitarray.py
> +        return out
The distinction between `bitarray.byte_reverse()`, `bitarray.byte_reversed()` and `bitarray.reversed()` is very subtle on first glance... perhaps a comment?

Also, some don't behave properly, or observe `self._len_` properly: 😬

```
>>> x = bitarray.from_bytes(b'abc', 8*4)
>>> x
bitarray('00000000011000110110001001100001')
>>> x.byte_reverse()
bitarray('00000000110001100100011010000110')
>>> x.byte_reversed()
bitarray('00000000011000110110001001100001')
>>> x.reversed()
bitarray('00000000011000010110001001100011')
```

2021-01-27 12:12 UTC, mndza commented on software/glasgow/support/bitarray.py
> +        dst_bytes = (length - 1) // 8 + 1
Added brackets in commit 42ee9a60112c9830144db40a08d70bcce6776e46

2021-01-27 12:13 UTC, mndza commented on software/glasgow/support/bitarray.py
> +        return inst
This is now fixed in commit b99b66f0764e9e584aa4235abe157391251397bc

2021-01-27 12:18 UTC, mndza commented on software/glasgow/support/bitarray.py
> +            self._array_[pos // 8] &= ~(1 << (pos % 8))
Fixed this in 0cc3898fda6ef115218170e4adf2d939326207a8, although not here but in the __getitem__ and __setitem__ methods.
__getbit and __setbit are private methods which may be used repeatedly and I wanted to avoid redundant checks.

2021-01-27 12:21 UTC, mndza commented on software/glasgow/support/bitarray.py
> +        return self & other
Fixed in 78e0654da295a1d4bfc1c09947e7ea71a865ba83.

2021-01-27 12:33 UTC, mndza commented on software/glasgow/support/bitarray.py
> +        return out
Yes, I know the distinction is not very clear (see my original PR message). I will add some docstrings, but maybe we could remove one of the methods (`byte_reverse` or `byte_reversed`) ?

The wrong result in `reversed()` was caused by the bug fixed in b99b66f0764e9e584aa4235abe157391251397bc.

Regarding `self._len_`:
- In `reversed()`, `self._len_` is used to determine how much padding should be added before the actual reverse process. Not seeing the problem here.
- In `byte_reverse()` / `byte_reversed()`, entire bytes are reversed, so the only thing I do when `self._len_` is not multiple of 8 is mask the final byte. I also stated my doubts about the correct operation here in the original PR. Could you explain what behavior are you expecting in this case? Then I may modify the method to comply.

2021-01-27 12:45 UTC, mndza commented on software/glasgow/support/bitarray.py
> +        return "bitarray('{}')".format(self)
This method is internally calling `to_str()` / `__str__` method, so I think we can ignore this case: `self._len_` is handled there.

2021-01-27 17:03 UTC, mndza commented on software/glasgow/support/bitarray.py
> +        self._array_ = array('B', value_bytes)
I still haven't found a way to do it faster than this. Regarding your concern, this code should in fact work for arbitrarily large numbers, as Python's `int` implementation is only limited by the amount of available memory.

I also tried some other approaches. The following runs at least 10x slower in my machine, testing with 1GiB `bitarray`:

```python
def setall(self, value):
    byte = 0xFF if bool(value) else 0
    self._array_ = array('B', bytes(byte for _ in range(len(self._array_))))
    if self._len_ % 8:
        self._array_[-1] &= ~(-1 << (self._len_ % 8))
```

2021-01-27 17:09 UTC, mndza commented on software/glasgow/applet/display/pdi/__init__.py
> +            image = bitarray(image_bytes, 8*len(image_bytes))
I was not trying to keep API compatibility with the external `bitarray` module, but to have a consistent API with the current `glasgow.support.bits` implementation.

As an example:
- `from_bytes()` in `glasgow.support.bits` is a class method that constructs a new object.
-  `frombytes()` in the external `bitarray` module extends the `bitarray` object with the provided bytes.

2021-01-27 17:17 UTC, mndza commented on software/glasgow/protocol/jesd3.py
> +        self.fuse = bitarray(0, int(count, 10))
Regarding endianness, the class currently only works in "little-endian" mode: least significant bytes are stored at the smallest address, and bits are ordered from LSB to MSB inside a byte. This is also consistent with `glasgow.support.bits`.

I am not sure if this is a problem though.

2021-01-27 17:21 UTC, mndza commented on software/glasgow/support/bitarray.py
> +    def __slice_bits(src, start=0, length=None, dst=None):
Agreed, fixed in 14691309688a0adcce67271c49632d2505d53712.

2021-01-27 17:45 UTC, mndza commented on software/glasgow/support/bitarray.py
> +        return dst
You are right. I will try to improve the comments here.

2021-01-27 18:35 UTC, mndza commented on software/glasgow/support/bitarray.py
> +            value &= ~(-1 << length)
This actually comes straight from `glasgow.support.bits`:

https://github.com/GlasgowEmbedded/glasgow/blob/b1985b3c46b7aebc426f70ca22c5f1e05376238b/software/glasgow/support/bits.py#L30

2021-01-27 18:47 UTC, mndza commented on software/glasgow/support/bitarray.py
> +        return cls.from_bytes(value.to_bytes(bytelen, "little"), length)
This should actually be expected due to the internal representation: bits in LSB to MSB order, bytes in least-to-most significant order. I am not sure about whether we should support additional endianness options.

2021-01-29 02:41 UTC, whitequark commented on software/glasgow/applet/display/pdi/__init__.py
> +            image = bitarray(image_bytes, 8*len(image_bytes))
I agree, this change is actually desirable.

2021-01-29 02:42 UTC, whitequark commented on software/glasgow/applet/program/xc6s/__init__.py
> +            bitstream = bits(ba.to_bytes(), len(ba))
It's not necessary to maintain any compatibility with the `bitarray` PyPI package, which is badly designed and is a constant source of bugs.

2021-01-29 02:43 UTC, whitequark commented on software/glasgow/protocol/jesd3.py
> +        self.fuse = bitarray(0, int(count, 10))
Endianness should emphatically *not* be a property of the new `bitarray` class. However, it must be possible to specify endianness when serializing/deserializing to/from buffer objects. E.g. SPI and JTAG have opposite endianness and we are actually going to hit this when working on gateware.

2021-01-29 02:45 UTC, whitequark commented on software/glasgow/protocol/jesd3.py
> +        self.fuse = bitarray(0, int(count, 10))
However, I can see that `glasgow.support.bits` does not have a way to do so. It's fine to extend both of them at the same time in a different PR, provided that existing `bitarray`-using code can be ported as it is.

2021-01-29 02:47 UTC, whitequark commented on software/glasgow/support/bitarray.py
> +            value &= ~(-1 << length)
That's just masking `value` to `length`. If you're OK operating on `value` you'll be OK creating another similarly sized integer.

2021-01-29 02:50 UTC, whitequark commented on software/glasgow/support/bitarray.py
> +        # Only perform operation in-place when the other bitarray is smaller
This seems like a wrong condition to pick between mutating and copying operations.

2021-01-29 17:17 UTC, mndza commented on software/glasgow/support/bitarray.py
> +        # Only perform operation in-place when the other bitarray is smaller
What would be the proper response when `other`'s bit length is larger? Maybe raise an exception like @attie (https://github.com/GlasgowEmbedded/glasgow/pull/265#discussion_r564905060) mentioned? If so, should that only happen for the in-place operations?

2021-02-15 15:52 UTC, mndza commented on software/glasgow/support/bitarray.py
> +        self._len_ = max(self._len_, other._len_)
Changed this in ffc277a56af114162cdb7ef050386c01b22b5672. Now in-place bit operations never change length.

2021-02-15 15:53 UTC, mndza commented on software/glasgow/support/bitarray.py
> +        # Only perform operation in-place when the other bitarray is smaller
Changed the behavior in commit ffc277a56af114162cdb7ef050386c01b22b5672

2023-07-01 23:31 UTC, whitequark requested changes
Thank you for your contribution. Unfortunately, while the basic approach to the task was sound, this particular implementation includes a substantial degree of complexity (e.g. the `__copy_bit_slice` method) and numerous issues (see inline comments), and as a result I cannot convince myself that we should merge it. Again unfortunately, I also do not expect that I will have the review bandwidth necessary to bring this implementation to the point where it would be mergeable.

I apologize for causing you to spend your time in this way. I think that some of the code in this PR could be reused by a future developer handling the same task, so hopefully it will have some utility in the end.

2023-07-01 23:31 UTC, closed without merging

2023-07-25 15:42 UTC, mndza commented
I do agree with you: looking at this code now (it's been a while) and I'm not happy with it. I should have targeted for simplicity and correctness first. My apologies.

2023-07-26 03:06 UTC, whitequark commented
Thank you for understanding. I'm happy to work with you on any future contributions, if you would like to.