cli: add --force-reload option to override bitstream id check in all cases
GlasgowEmbedded/glasgow pull request #275
Opened 2021-02-15 04:31 UTC by TomKeddie

2021-02-15 11:39 UTC, attie commented
Is this significantly different to `--rebuild`?
What is the use case for `--force-reload` over `--rebuild`?

2021-02-15 14:58 UTC, TomKeddie commented
@attie thanks for your comments.   In the mainstream case there is no difference.  I'm using this where I supply the bitstream, built outside of glasgow, where the id is not valid and I want it to be reloaded.   I guess I could overload ```--rebuild``` to reload in the cases where an image was supplied and avoid the extra option, would that be appropriate.

2021-02-15 15:05 UTC, attie commented
> I'm using this where I supply the bitstream, built outside of glasgow, where the id is not valid and I want it to be reloaded.

Ah, I see.

I presume you're using this in conjunction with `--prebuilt-at`? If so, perhaps something else should be used in place of the bitstream's ID for external bitstreams (e.g: a hash of the binary file)? This way we could remove the extra flag, and it would always reload when required...?

2021-02-15 15:11 UTC, whitequark commented
Alternatively a bitstream ID of all ones could be used to indicate "always reload".

2021-02-15 15:20 UTC, TomKeddie commented
> Alternatively a bitstream ID of all ones could be used to indicate "always reload".

I'll update the PR to do this,  great idea.

2021-02-15 15:43 UTC, TomKeddie commented
Done.  Please squash when merging to hide the mess.

2021-02-15 15:47 UTC, attie commented
@TomKeddie please could you rebase/squash and force-push when you're happy?

(It looks like `software/glasgow/cli.py` still need to be cleaned up)

2021-02-15 15:51 UTC, attie requested changes

2021-02-15 15:51 UTC, attie commented on software/glasgow/device/hardware.py
> +        elif bitstream_file_id != plan.bitstream_id and not force_download:
This should probably fall into its own `elif` with a more accurate warning.

2021-02-15 15:51 UTC, attie commented on software/glasgow/cli.py
> +            help="(advanced) force reload of bitstream")
Remove

2021-02-15 15:51 UTC, attie commented on software/glasgow/cli.py
> +                    await device.download_prebuilt(plan, bitstream_file, force_reload=args.force_reload)
Revert

2021-02-15 15:51 UTC, attie commented on software/glasgow/cli.py
> +                await device.download_target(plan, rebuild=args.rebuild, force_reload=args.force_reload)
Revert

2021-02-15 16:29 UTC, TomKeddie commented on software/glasgow/cli.py
> +                await device.download_target(plan, rebuild=args.rebuild, force_reload=args.force_reload)
Sorry I missed commiting a local change, will squash etc as requested.

2021-02-15 17:00 UTC, attie commented
Thanks @TomKeddie.

Not sure if there's a preference either way for `bytearray('\xff' * 16, 'latin-1')` vs `b'\xff' * 16` - I'd pick the latter, but take @whitequark's lead.

LGTM.

2021-02-17 13:00 UTC, whitequark approved these changes

2021-02-17 13:01 UTC, merged

2021-02-17 13:01 UTC, whitequark commented
Thanks!