Introduce a plugin system that handles fine grained dependencies, and use it for applets
GlasgowEmbedded/glasgow pull request #357
Opened 2023-07-24 01:37 UTC by whitequark

This PR introduces three related changes:
* Instead of the awful applet registration in `glasgow.applet.all`, entry points are now used.
* Instead of requiring every dependency of every applet to be installed just to run `glasgow --help`, applets now specify their own dependencies, and missing dependencies are gracefully handled by replacing applet help with instructions for installing them.
* The system underlying the above is generalized so that it can be used to handle similar collections of tools in other parts of the codebase, of which we have at least two (applet tools and data loggers).

This is essentially the implementation of the plan outlined in https://github.com/GlasgowEmbedded/glasgow/issues/234#issuecomment-733584629.

It also paves way for out-of-tree applets. (At the moment they are explicitly forbidden to avoid creating a backwards compatibility hazard.)

2023-07-29 07:37 UTC, whitequark commented
@attie Note that the commits all have *long* descriptions, for you to read!

2023-07-31 01:00 UTC, attie requested changes
In the last commit, `software.glasgow.cli:_applet()` needs updating:
`GlasgowAppletUnavailable` -> `PluginRequirementsUnmet`

---

Otherwise, looks very good!

2023-07-31 01:21 UTC, whitequark commented on software/glasgow/cli.py
> +        for applet_name, applet_meta in GlasgowAppletMetadata.all().items():
I think it's fine. Our performance isn't going to improve until we stop actually loading Python code when constructing the CLI, which is ways off.

2023-07-31 01:22 UTC, whitequark commented on software/glasgow/cli.py
> +            tool = GlasgowAppletMetadata.get(args.applet).cls.tool_cls()
Functional history?

2023-07-31 01:23 UTC, attie commented on software/glasgow/cli.py
> +            tool = GlasgowAppletMetadata.get(args.applet).cls.tool_cls()
I don't remember what it's called, but the "every commit works" concept.

2023-07-31 01:24 UTC, whitequark commented on software/glasgow/cli.py
> +            tool = GlasgowAppletMetadata.get(args.applet).cls.tool_cls()
Ah, right. I'll check that.

2023-07-31 01:49 UTC, whitequark commented on software/glasgow/cli.py
> +            tool = GlasgowAppletMetadata.get(args.applet).cls.tool_cls()
All commits should individually work now.

2023-07-31 01:49 UTC, whitequark commented on software/glasgow/cli.py
> +        raise SystemExit()
Fixed.

2023-07-31 01:49 UTC, whitequark commented on software/glasgow/cli.py
> +        raise SystemExit()
Fixed.

2023-07-31 18:03 UTC, attie approved these changes
Fantastic, thanks very much!

2023-07-31 18:35 UTC, attie commented
... one downside to this, is that we need to `pip install .../path/to/glasgow/software` again if we add a new applet.

Certainly manageable, but might trip people up.

2023-07-31 20:18 UTC, electroniceel commented
> ... one downside to this, is that we need to `pip install .../path/to/glasgow/software` again if we add a new applet.

you mean adding a new applet that needs some new dependency, or even when adding a new applet that doesn't need any new dependency?

I haven't used the new entry-point stuff of setuptools yet, so I might be missing something here. But shouldn't the entry-point feature take care of making all the applets available, even if you change the pyproject.toml?

2023-07-31 20:58 UTC, attie commented
> you mean adding a new applet that needs some new dependency, or even when adding a new applet that doesn't need any new dependency?

Any new applet seems to require a reinstall, even if you used `pip install -e`

> But shouldn't the entry-point feature take care of making all the applets available, even if you change the pyproject.toml?

With `-e`, I would have expected / hoped so, but it seems to not be the case... Without `-e`, I wouldn't expect it.

2023-08-01 08:06 UTC, whitequark commented
> ... one downside to this, is that we need to `pip install .../path/to/glasgow/software` again if we add a new applet.

This is already in README by the way.

> With `-e`, I would have hoped so (but not really expect it), but it seems to not be the case... Without `-e`, I wouldn't expect it.

There's no really good way to do this infrastructurally even with `-e`. And I think this is just something people using the Glasgow software will need to learn.

2023-08-01 08:20 UTC, merged

2023-08-01 15:58 UTC, attie commented
Indeed it is... in light of this PR, how would you feel about me/you changing:

> Changes to pyproject.toml, most importantly to the dependencies, are not picked up until pipx reinstall is manually run.

to:

> Changes to pyproject.toml, most importantly to the dependencies **or list of applet entrypoints**, are not picked up until pipx reinstall is manually run.

2023-08-01 16:03 UTC, whitequark commented
Yes absolutely.

2023-08-01 16:13 UTC, attie commented
Great - see #379