Make iManufacturer configurable in factory flow
GlasgowEmbedded/glasgow pull request #358
Opened 2023-07-24 02:43 UTC by whitequark

Fixes https://github.com/GlasgowEmbedded/glasgow/issues/347.

2023-07-24 06:37 UTC, whitequark commented
Note to self: merge after #361

2023-07-27 23:36 UTC, esden approved these changes
This LGTM, I have tested this to provision a Glasgow and the iManufacturer is being set correctly.

2023-07-28 00:05 UTC, attie requested changes

2023-07-28 00:05 UTC, attie commented on software/glasgow/device/config.py
> +                           self.manufacturer.encode("ascii"))
The default `None` makes this break... giving `b''` works.

```
Traceback (most recent call last):
  File "/usr/local/bin/glasgow", line 8, in <module>
    sys.exit(main())
  File "/opt/glasgow/software/glasgow/cli.py", line 876, in main
    exit(loop.run_until_complete(_main()))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/glasgow/software/glasgow/cli.py", line 828, in _main
    fx2_config.append(0x4000 - GlasgowConfig.size, glasgow_config.encode())
  File "/opt/glasgow/software/glasgow/device/config.py", line 88, in encode
    self.manufacturer.encode("ascii"))
AttributeError: 'NoneType' object has no attribute 'encode'
```

2023-07-28 00:45 UTC, whitequark commented on software/glasgow/device/config.py
> +                           self.manufacturer.encode("ascii"))
Fixed

2023-07-28 01:15 UTC, attie approved these changes
Thank you!

2023-07-28 02:00 UTC, merged