applet.interface.spi_serprog: New applet that implements the Flashrom Serprog protocol
GlasgowEmbedded/glasgow pull request #506
Opened 2024-01-05 06:04 UTC by neuschaefer

So far this is a draft, and will likely require improvements in a few ways; I'm thankful for any pointers in that regard.

I have however tested this applet with two different flash chips and it seems to work fine.

## TODO

- [ ] Upload serprog.h and serprog-protocol.txt to the archive repo

2024-01-05 10:48 UTC, whitequark commented
This PR fails CI.

2024-01-05 11:15 UTC, whitequark requested changes

2024-01-05 11:15 UTC, whitequark commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +        super().add_run_arguments(parser, access)
All of this is extraneous.

```suggestion
```

2024-01-05 11:15 UTC, whitequark commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +        return super().build_subtarget(target, args)
Extraneous.
```suggestion
```

2024-01-05 11:15 UTC, whitequark commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +        self.assertBuilds()
I don't think you need an `assertBuilds` test if you add no gateware.

2024-01-05 11:15 UTC, whitequark commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +                except asyncio.CancelledError:
I *think* this is the default behavior? What happens if you remove the `try/except`?

2024-01-05 11:15 UTC, whitequark commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +        await asyncio.wait([handle_fut], return_when=asyncio.FIRST_EXCEPTION)
I think this is exactly the same as `await handle()`? So you can inline the entire loop into `interact()`.

2024-01-05 11:15 UTC, whitequark commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +        return await self.lower.read(rlen)
Two lines between every top-level entity. (This and a few other extremely basic stylistic requirements is something I might add a flake8 job for...)

2024-01-05 11:15 UTC, whitequark commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +    S_ACK               = 0x06
I think this entire command list should be an enum, with the docstring pointing to these files.

2024-01-05 11:15 UTC, whitequark commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +        return sum([x << 8 * i for i, x in enumerate(data)])
I would use `int.from_bytes`/`int.to_bytes`. Also, I would probably not add such a generic mechanism at all with a function per size when inlining it at every point of use would reduce the LOC count by like 20.

2024-01-05 11:16 UTC, whitequark commented
Thanks for working on this! I think flashrom support could be quite useful, for the same reasons we have both `jtag-openocd` and other JTAG options.

2024-01-05 11:44 UTC, neuschaefer commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +        self.assertBuilds()
good point

2024-01-05 11:46 UTC, neuschaefer commented
@whitequark thanks for the review! I'll get back to it in detail later

2024-01-06 23:07 UTC, neuschaefer commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +                except asyncio.CancelledError:
It seems to fail in the same way (with or without try/except) when I inject a fault by unplugging the glasgow.

2024-01-06 23:07 UTC, neuschaefer commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +        self.assertBuilds()
removed the whole testcase

2024-01-06 23:07 UTC, neuschaefer commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +        return super().build_subtarget(target, args)
done

2024-01-06 23:08 UTC, neuschaefer commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +        super().add_run_arguments(parser, access)
done

2024-01-06 23:08 UTC, whitequark commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +                except asyncio.CancelledError:
I think that doesn't result in cancellation, but rather another exception being raised.

2024-01-10 22:05 UTC, whitequark reviewed
Code looks OK now, aside from style. (Please do fix that!)

I will merge this sometime soon when I find time to test it with a flash myself. I will probably reword the applet description a bit.

Would you like to become the code owner for the new applet?

2024-01-10 22:07 UTC, whitequark commented
Also, just to be clear: I think flake8's default settings are a net negative, but there is a small subset that we do already require (but don't have written dwon anywhere) and so it's easier to automate that.

2024-01-11 02:47 UTC, neuschaefer commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +        return await self.lower.read(rlen)
Double blank lines between toplevel items: done

2024-01-11 02:50 UTC, whitequark commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +        await asyncio.wait([handle_fut], return_when=asyncio.FIRST_EXCEPTION)
Ah, right. If I remember correctly, just `await asyncio.ensure_future(handle())` will behave the way you want wrt cancellation.

2024-01-11 02:52 UTC, neuschaefer commented
I don't fully understand the coroutine and exception stuff here, but upon further testing I discovered the following:

- Without the try/except block, the applet stops after the first client disconnects, which I found somewhat undesirable. With it, multiple consecutive connections are accepted, until the applet is terminated explicitly.
- Without spawning a coroutine for the handler, I have to press ^C twice to terminate the applet, and it prints a python backtrace. With the coroutine, one ^C terminates the applet cleanly.

So I reintroduced these two things in the last two commits

2024-01-11 02:55 UTC, neuschaefer commented
> Would you like to become the code owner for the new applet?

If that simply entails that I'll be pinged on pull requests changing this applet. yes please. I can at least review the serprog-specific details.

2024-01-11 02:56 UTC, whitequark commented
> If that simply entails that I'll be pinged on pull requests changing this applet.

Pretty much. You can add yourself to the CODEOWNERS file then. I think I'll also need to add you to the org.

2024-01-11 02:57 UTC, neuschaefer commented
I thought about adding serprog.h and serprog-protocol.txt to the archive repo, but since the "vendor" in this case is another open source project, it doesn't seem so necessary

2024-01-11 18:58 UTC, neuschaefer commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +        await asyncio.wait([handle_fut], return_when=asyncio.FIRST_EXCEPTION)
Unfortunately not

2024-01-13 16:10 UTC, neuschaefer commented
> I will probably reword the applet description a bit.

The formatting is a bit broken too (in --help output), but I'll leave it as is for now, if you're going to reword the text anyway

2024-01-16 08:33 UTC, neuschaefer commented
I can squash the commits that need squashing, when it's convenient for you

2024-03-05 23:41 UTC, whitequark commented
I'm currently reviewing this applet locally. I'm making a number of changes, which I'll squash into the commit introducing the applet but describe here:
- Rename from `spi-serprog` to `spi-flashrom` (like `jtag-openocd`); it appears that "serprog" is just "flashrom's private protocol" rather than anything established.
- Rewrite the documentation to be more concise and closer to that of `jtag-openocd`.
- Add cross-links between `spi-flashrom` and `memory-25x` help text, to make the operator aware of the alternative in both cases.
- Remove "preview" flag from the applet since it seems reasonably mature to me.
- Add "hold" and "wp" pin assignments, which are necessary to read many flashes when they're in a clip because by default or chance the flash would end up either write-protected (if WP is active) or just non-communicative at all (if HOLD is active); I encountered this issue during testing. The `memory-25x` applet handles this.

2024-03-06 00:14 UTC, whitequark approved these changes
Thank you for your excellent work on this applet!

2024-03-06 00:14 UTC, whitequark commented on software/glasgow/applet/interface/spi_serprog/__init__.py
> +        await asyncio.wait([handle_fut], return_when=asyncio.FIRST_EXCEPTION)
Yep you're right, I had to add this back. What an unintuitive library...

2024-03-06 00:17 UTC, merged