F improvements for mec16xx
GlasgowEmbedded/glasgow pull request #507
Opened 2024-01-07 15:25 UTC by purdeaandrei

Please see individual commits for details and commit messages.
Let me know if you'd want to split this up as separate PRs.

2024-01-08 00:00 UTC, whitequark commented on software/glasgow/applet/program/mec16xx/__init__.py
> +        self._logger.log(logging.WARNING, "After running emergency mass erase, a power cycle may be required on some chips.")
I think we usually use something like

```suggestion
        self._logger.warn("After running emergency mass erase, a power cycle may be required on some chips.")
```

(I may be misremembering)

2024-01-08 00:04 UTC, whitequark commented on software/glasgow/applet/program/mec16xx/__init__.py
> +            "erase-flash", help="erase the flash memory only using normal flash controller " +
I would go for:

```suggestion
            "erase", help="erase EC firmware (non-emergency mode)"
```

then reword the other one to

```suggestion
            "emergency-erase", help="erase EC firmware (emergency mode)")
```

and add a short description of the difference in the main help text, since it's a bit too long to be put inline in the operations.

2024-01-08 00:05 UTC, whitequark commented on software/glasgow/applet/program/mec16xx/__init__.py
> +            "even in the case of boot code corruption.")
Ah, I've looked at the previous commit before this one. My comments stand; this explanation would benefit from being in the main help text.

2024-01-08 00:05 UTC, whitequark commented on software/glasgow/applet/program/mec16xx/__init__.py
> +            "read-eeprom", help="read eeprom")
I would prefer if all the other commands were renamed to have a `-flash` suffix after introducing the `-eeprom` ones. (The CLI isn't generally considered stable so we can just change it.)

2024-01-08 00:06 UTC, whitequark commented on software/glasgow/applet/program/mec16xx/__init__.py
> +            "password", metavar="PASSWORD", type=lambda x: int(x, 0), help="password to try to unlock with")
I would make this lambda into a `def` function because argparse treats the function name specially (it displays it on parse failure, try supplying an invalid argument and you'll see). There are examples of this elsewhere in the codebase.

2024-01-08 00:07 UTC, whitequark requested changes
Congratulations on a fantastic first-time contribution! Your PR is excellent and I look forward to working with you more in the future. All I have is some minor stylistic changes.

Would you like to become the code owner for this applet?

2024-01-14 08:59 UTC, purdeaandrei commented on software/glasgow/applet/program/mec16xx/__init__.py
> +            "erase-flash", help="erase the flash memory only using normal flash controller " +
done

2024-01-14 08:59 UTC, purdeaandrei commented on software/glasgow/applet/program/mec16xx/__init__.py
> +            "read-eeprom", help="read eeprom")
done

2024-01-14 08:59 UTC, purdeaandrei commented on software/glasgow/applet/program/mec16xx/__init__.py
> +            "password", metavar="PASSWORD", type=lambda x: int(x, 0), help="password to try to unlock with")
done

2024-01-14 08:59 UTC, purdeaandrei commented on software/glasgow/applet/program/mec16xx/__init__.py
> +            "even in the case of boot code corruption.")
done

2024-01-14 09:06 UTC, purdeaandrei commented
Ready for re-review.

Note that this patchset now includes the commit from https://github.com/GlasgowEmbedded/glasgow/pull/514 (as first in the patch set), since it's a dependency
I have squashed some changes into the previously reviewed commits.

Commits with completely new code, at the end of the patch set are:

https://github.com/GlasgowEmbedded/glasgow/pull/507/commits/32a9cc8bf1abfd9ef182bbc034a89e8beec8ad1a
https://github.com/GlasgowEmbedded/glasgow/pull/507/commits/a8afa097f7115ead4fbc2cf6f514b12db5a07cf7
https://github.com/GlasgowEmbedded/glasgow/pull/507/commits/3bd5160b4e220b2edce25378caffd8825ce5b4d9
https://github.com/GlasgowEmbedded/glasgow/pull/507/commits/a425aa95a57185ed95caa632c00d6edd954b4d15
https://github.com/GlasgowEmbedded/glasgow/pull/507/commits/7e726b9470d508050f1377a8bcf65063a506205a
https://github.com/GlasgowEmbedded/glasgow/pull/507/commits/3df2adf37a53a6af209dbb0abb87b4460708c4ae

I think with this I consider the program-mec16xx applet complete.

2024-01-14 09:16 UTC, purdeaandrei commented
Also added: https://github.com/GlasgowEmbedded/glasgow/pull/507/commits/e56583132eb9e8fc7b4890fe82879129958b1485

2024-01-14 10:28 UTC, purdeaandrei commented
Rebased, typos fixed

2024-01-21 17:18 UTC, whitequark approved these changes
Thank you for this excellent contribution!

2024-01-21 17:21 UTC, merged