applet.interface.jtag_openocd: Document how to improve performance
GlasgowEmbedded/glasgow pull request #522
Opened 2024-01-21 19:11 UTC by neuschaefer

The jtag_openocd gateware performs all the necessary delays to achieve the configured clock frequency, but by default OpenOCD inserts additional delays on the client side. By using the newly introduced "use_remote_sleep on" option these delays can be disabled; On older versions of OpenOCD, the "adapter speed" can be increased to minimize the delays.

2024-01-21 19:14 UTC, whitequark requested changes
We need to actually implement remote sleep before recommending it in the docs.

2024-01-21 19:15 UTC, neuschaefer commented
Hm, in that case I may have misunderstood the feature

2024-01-21 19:17 UTC, whitequark commented
> Hm, in that case I may have misunderstood the feature

It is an extension of the protocol that Glasgow does not yet implement. It's easy to implement though.

2024-03-05 23:01 UTC, whitequark commented
I'm going to close this PR since the doc addition is inaccurate and will result in subtle breakage if followed.

2024-03-05 23:01 UTC, closed without merging