applets: Remove a few unicode characters that caused problems on Windows mingw terminal
GlasgowEmbedded/glasgow pull request #547
Opened 2024-03-28 01:54 UTC by colinoflynn

Thanks to Window's great unicode support, a few help strings caused errors. It's not obvious to a user as the traces look like this, the first one (for the sigma-delta DAC) doesn't even give you a character to look up:

```
$ glasgow.exe run --help
Traceback (most recent call last):
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\users\c_ofl\.local\bin\glasgow.exe\__main__.py", line 7, in <module>
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\chipwhisperer\jupyter\user\glasgow\glasgow\software\glasgow\cli.py", line 940, in main
    exit(loop.run_until_complete(_main()))
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\chipwhisperer\jupyter\user\glasgow\glasgow\software\glasgow\cli.py", line 518, in _main
    args = get_argparser().parse_args()
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 1826, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 2050, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 2027, in consume_positionals
    take_action(action, args)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 1214, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 2068, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 2008, in consume_optional
    take_action(action, args, option_string)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 1099, in __call__
    parser.print_help()
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 2556, in print_help
    self._print_message(self.format_help(), file)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 2562, in _print_message
    file.write(message)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 345-346: character maps to <undefined>
```

```
$ glasgow.exe run --help
Traceback (most recent call last):
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\users\c_ofl\.local\bin\glasgow.exe\__main__.py", line 7, in <module>
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\chipwhisperer\jupyter\user\glasgow\glasgow\software\glasgow\cli.py", line 940, in main
    exit(loop.run_until_complete(_main()))
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\chipwhisperer\jupyter\user\glasgow\glasgow\software\glasgow\cli.py", line 518, in _main
    args = get_argparser().parse_args()
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 1826, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 2050, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 2027, in consume_positionals
    take_action(action, args)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 1214, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 2068, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 2008, in consume_optional
    take_action(action, args, option_string)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 1099, in __call__
    parser.print_help()
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 2556, in print_help
    self._print_message(self.format_help(), file)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\argparse.py", line 2562, in _print_message
    file.write(message)
  File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2082' in position 3943: character maps to <undefined>
```

To troubleshoot I had temporarily done this in `cli.py`:

Starting at line 167 for context:
```
            if applet_cls.required_revision > "A0":
                help += f" (rev{applet_cls.required_revision}+)"
                description += "\n    This applet requires Glasgow rev{} or later." \
                               .format(applet_cls.required_revision)
+           try:
+               print(help)
+           except [...]

2024-03-28 01:57 UTC, whitequark requested changes
Absolutely not. It is 2024. I expect my OS (any OS) to support Unicode.

2024-03-28 01:59 UTC, whitequark commented
I suspect this is related to your Python installation. If you install Python from https://python.org as it's recommended in the guide, does it appear?

2024-03-28 02:22 UTC, colinoflynn commented
I'm assuming it's something "install-specific" (I was assuming terminal, but maybe Python install). Will check with a fresh one on same terminal, but might be a bit before I get to it. I'm OK to close this out instead for now so it doesn't become a zombie!

FWIW I was using this install as (you can see from path) using it w/ ChipWhisperer, so was keeping on a version working with that. I just assumed the cp1252 was coming from my terminal, but will check the install. 

I may check if there is a way to improve error reporting (e.g., if someone else has an environment problem, they don't raise issues needlessly but can figure out what to either fix or hack out of the description) & if so will open that as a separate solution.

Thanks again for quick feedback, looking forward to working with Glasgow!

2024-03-28 02:38 UTC, whitequark commented
> I may check if there is a way to improve error reporting (e.g., if someone else has an environment problem, they don't raise issues needlessly but can figure out what to either fix or hack out of the description) & if so will open that as a separate solution.

There might be a way to set the encoding parameters so that it replaces unencodable characters with something instead of dying.

2024-03-28 02:39 UTC, whitequark commented
Try any of these environment variables:

```
set PYTHONUTF8=1
set PYTHONIOENCODING=utf-8
set PYTHONLEGACYWINDOWSSTDIO=utf-8
```

2024-03-29 17:09 UTC, colinoflynn commented
Both of the first two did work, I had tried another env. vars before, but they were setting the terminal default, but those ones did it, testing like:

```
PYTHONUTF8=1  glasgow run --help
PYTHONIOENCODING=utf-8  glasgow run --help
```

In which case the terminal is happy to print the unicode, so indeed was the default install problem. I can confirm this by running:

```
$ python -c "import locale; print(locale.getpreferredencoding());"
cp1252

$ PYTHONUTF8=1 python -c "import locale; print(locale.getpreferredencoding());"
UTF-8
```

Not sure if there is a good/sane automated way to test this somewhere, or it's just a documented note (agree that non-utf8 python default isn't expected). I'm going to close the PR since the actual PR contents here don't make sense...

2024-03-29 17:09 UTC, closed without merging