protocol.nbd: implement Network Block Device server.
GlasgowEmbedded/glasgow pull request #587
Opened 2024-06-21 08:51 UTC by neuschaefer

2024-06-21 09:02 UTC, whitequark commented
The overall structure looks good at a quick glance, and the functionality as a whole is very desirable. I assume you'll address a variety of minor issues before you un-draft the PR.

2024-06-21 09:19 UTC, neuschaefer commented
> I assume you'll address a variety of minor issues before you un-draft the PR.

Yes. I have a few TODO notes in there, which I'll address before un-drafting. (No timeframe though.)

2024-07-12 21:39 UTC, neuschaefer commented
I probably still missed something, but I think it's ready for review now.

2024-07-13 05:34 UTC, whitequark commented on software/glasgow/protocol/nbd.py
> +# https://github.com/NetworkBlockDevice/nbd/blob/master/nbd.h
Please add these files to our documentation archive.

2024-07-13 05:36 UTC, whitequark requested changes
I did a first pass mainly on style, I'll do another when I feel a bit better.

2024-07-13 05:36 UTC, whitequark commented on software/glasgow/protocol/nbd.py
> +
```suggestion


```

2024-07-13 05:36 UTC, whitequark commented on software/glasgow/protocol/nbd.py
> +
```suggestion


```

2024-07-13 05:36 UTC, whitequark commented on software/glasgow/protocol/nbd.py
> +
```suggestion


```

2024-07-13 05:36 UTC, whitequark commented on software/glasgow/protocol/nbd.py
> +
```suggestion


```

2024-07-13 05:36 UTC, whitequark commented on software/glasgow/protocol/nbd.py
> +if __name__ == '__main__':
I would prefer it if you had all of the argparse logic within an argument-less `main` (or perhaps taking `argv` as an argument), otherwise importing this function requires you to know a private interface.

2024-07-21 22:09 UTC, whitequark commented on software/glasgow/protocol/nbd.py
> +# https://github.com/NetworkBlockDevice/nbd/blob/master/nbd.h
Please add a reference to the archive in the header. See [this link](https://glasgow-embedded.org/latest/contribute.html#vendor-documentation) for the format.

2024-07-21 22:10 UTC, whitequark commented on software/glasgow/protocol/nbd.py
> +async def main():
```suggestion

async def main():
```

2024-07-21 22:10 UTC, whitequark commented on software/glasgow/protocol/nbd.py
> +if __name__ == '__main__':
```suggestion

if __name__ == '__main__':
```

2024-07-21 22:11 UTC, whitequark commented on software/glasgow/protocol/nbd.py
> +        self.logger.trace(f'Client flags: {client_flags}')
By convention all of the logger messages start with a lowercase character.

2024-07-21 22:11 UTC, whitequark reviewed
I replied with a last round of style fixes, after that I'll merge it. Thanks for doing this work again!

2024-07-21 22:13 UTC, whitequark commented
The implementation of the protocol seems like it would suffer in performance due to the heavy use of sub-coroutines to read individual fields rather than packing/unpacking them in bulk, but I don't think this needs to be fixed now; it may not ever be a problem, and if it does, it can be fixed then.

2024-08-10 21:45 UTC, neuschaefer commented on software/glasgow/protocol/nbd.py
> +        self.logger.trace(f'Client flags: {client_flags}')
Does this apply to error messages in exceptions as well?

2024-08-10 21:47 UTC, whitequark commented on software/glasgow/protocol/nbd.py
> +        self.logger.trace(f'Client flags: {client_flags}')
To error messages in specifically exceptions that are derived from `GlasgowAppletError`. (Yeah, I know, this is kind of a mess and it's not documented anywhere rn...)

2024-08-10 21:52 UTC, neuschaefer commented on software/glasgow/protocol/nbd.py
> +async def main():
done

2024-08-10 21:53 UTC, neuschaefer commented on software/glasgow/protocol/nbd.py
> +        self.logger.trace(f'Client flags: {client_flags}')
ok, I've changed the `logger`  messages to lowercase, and left the `RuntimeError` messages as-is

2024-08-10 22:37 UTC, whitequark commented on software/glasgow/protocol/nbd.py
> +        self.writable = writable
Please make these fields private. (Also, could you rename `self.ep` to `self._endpoint` please?)

2024-08-10 22:38 UTC, whitequark reviewed
Looks like there are only two outstanding items:
- header comment
- privatizing fields

2024-08-10 22:59 UTC, neuschaefer commented
> Looks like there are only two outstanding items:
> 
>     * header comment
> 
>     * privatizing fields

The header comment should be there now (I previously held git wrong and the change wasn't included in my push); the fields I'll do later (tomorrow).

2024-08-10 23:08 UTC, whitequark commented
Thanks!

2024-08-11 09:14 UTC, neuschaefer commented on software/glasgow/protocol/nbd.py
> +        self.writable = writable
both done

2024-08-12 01:30 UTC, whitequark approved these changes
Thanks a lot for this effort!

2024-08-12 01:33 UTC, merged